package com.github.tutorial_about_java_60;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.ResponseBody;

/*
[The first annotation] means that this class is a Controller

[The second annotation causes all] URL's [to] start with /demo (after Application path)
*/
@Controller
@RequestMapping(path="/demo")
public class MainController {
    
    /*
    [This annotation says] to get the bean called `userRepository`
    which is auto-generated by Spring [and which] we will use ... to handle the data
    */
    @Autowired
    private UserRepository userRepository;

    /*
    `@ResponseBody` means
    the returned String is the response, not the name of a view template

    `RequestParam` [signifies]
    a parameter from the HTTP request
    */
    @PostMapping(path="/add")
    public @ResponseBody String addNewUser(
        @RequestParam
        String name,
        @RequestParam
        String email,
        @RequestParam
        String zipCode
    ) {
        User n = new User();
        n.setName(name);
        n.setEmail(email);
        System.out.println("zipCode: %s".formatted(zipCode));
        n.setZipCode(zipCode);
        userRepository.save(n);
        return "Saved";
    }

    @GetMapping(path="/all")
    public @ResponseBody Iterable<User> getAllUsers() {
        // This returns a JSON or XML with the users
        return userRepository.findAll();
    }
}
